services:
  ollama:
    image: ollama/ollama:rocm
    container_name: ollama_service
    devices:
      - "/dev/kfd"
      - "/dev/dri"
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
